### PR TITLE
installation update

### PR DESCRIPTION
**Pull request by aburrell**
Updated makebin.* files to use XPATH environment variable instead of
hardcoding X11 library directory

Updated README.md to include macOS dependencies, list of all
environment variables that need to be updated, and solutions to
problems encountered during macOS sierra installation.

### CODE REVIEW

**Comment by egthomas** [comment]
Thanks Angeline!  Just quickly looking through this, I'm not sure that changing to the `$RSTPATH/build/script` directory is necessary for executing `make.build` or `make.code` (at least for Linux).

**Comment by aburrell** [comment]
Thanks Evan!  I changed step three to show the change of directory as an option.

**Comment by egthomas** [comment]
Looks good.  Is there anyone else with a Mac who can replicate the compilation errors alluded to in steps 4a and 4b?  I have a feeling 4a (the workaround in make.code for users with access to IDL) might be related to some bash inconsistencies between linux and darwin.

**Comment by ksterne** [comment]
For what it's worth, I was able to get this to compile on Ubuntu 12.  Not sure if the xpath is set correctly though.  I also didn't run through the entire install process.  Just did another 'make.build' and then 'make.code superdarn rst' and didn't get any errors.

**Comment by aburrell** [comment]
Always good to check and see I didn't break anything :-P

**Comment by egthomas** [comment]
I was able to borrow a Mac from our IT guys so I'll try debugging some of this stuff today.

**Comment by egthomas** [comment]
Ok so I'm having mixed results here.  In the macOS column of the readme file, found one small typo: `netpdm` should be changed to `netpbm`.  Unfortunately `make.code superdarn rst` is consistently failing at compiling the fontdb.1.9 library.  @aburrell - did you encounter this?

**Comment by egthomas** [comment]
On another note, the IDL skip in `make.code` worked correctly on this system (MacOS Sierra 10.12.4).

**Comment by aburrell** [comment]
Fun!  I’m liking mac less right now.  I have the same operating system, but (obviously) got different failures.  Didn’t have any problem with fontdb.1.9.

**Comment by egthomas** [comment]
It's entirely possible I'm still missing some packages since I'm a total macports (and Mac) noob.  In particular, I could only find ncurses but not libcurses with macports:

The following ports are currently installed:
  bzip2 @1.0.6_0 (active)
  cdf @3.6.4_0 (active)
  curl @7.54.0_0+ssl (active)
  curl-ca-bundle @7.54.0_0 (active)
  db48 @4.8.30_4 (active)
  expat @2.2.0_0 (active)
  gettext @0.19.8.1_0 (active)
  hdf5 @1.10.1_0+cxx+hl (active)
  hdf5-18 @1.8.18_0+cxx+hl (active)
  jasper @2.0.12_0 (active)
  jbigkit @2.1_0 (active)
  jpeg @9b_0 (active)
  libedit @20170329-3.1_0 (active)
  libiconv @1.15_0 (active)
  libnetpbm @10.77.03_0 (active)
  libpng @1.6.29_0 (active)
  libxml2 @2.9.4_1 (active)
  ncurses @6.0-20170422_0 (active)
  netcdf @4.4.1_3+dap+netcdf4 (active)
  netpbm @10.77.03_2+x11 (active)
  openssl @1.0.2k_0 (active)
  python2_select @0.0_2 (active)
  python27 @2.7.13_1 (active)
  python_select @0.3_7 (active)
  sqlite3 @3.19.1_0 (active)
  tiff @4.0.8_0 (active)
  xorg-kbproto @1.0.7_0 (active)
  xorg-libpthread-stubs @0.3_0 (active)
  xorg-libX11 @1.6.4_0 (active)
  xorg-libXau @1.0.8_0 (active)
  xorg-libxcb @1.12_2+python27 (active)
  xorg-libXdmcp @1.1.2_0 (active)
  xorg-xcb-proto @1.12_1+python27 (active)
  xorg-xproto @7.0.31_0 (active)
  xz @5.2.3_0 (active)
  zlib @1.2.11_0 (active)

**Comment by aburrell** [comment]
If you check /opt/local/lib do you see libncurses?  It might just install with ncurses.  It was already installed on my system, so I didn’t have to go add it.

**Comment by egthomas** [comment]
I do see libncurses there.  Looking more closely at the error at fontdb.1.9, it appears to be failing on a call to sprintf from a /usr/include/secure/_stdio.h file (rather than /usr/include/stdio.h):

```
================================================================================
Compiling Library:/Users/thayer/f002s80/rst/codebase/base/src.lib/graphic/fontdb.1.9
================================================================================
make clean
rm -f *.o
make
make.version /Users/thayer/f002s80/rst/codebase/base/src.lib/graphic/fontdb.1.9/src/..
make.hdr /Users/thayer/f002s80/rst/codebase/base/src.lib/graphic/fontdb.1.9/src/../include /Users/thayer/f002s80/rst/include/base 
/Users/thayer/f002s80/rst/codebase/base/src.lib/graphic/fontdb.1.9/src/../include/fontdb.h
/Users/thayer/f002s80/rst/codebase/base/src.lib/graphic/fontdb.1.9/src/../include/fontdb.h -> /Users/thayer/f002s80/rst/include/base/fontdb.h
cc -Wall -O3 -ansi -D_GNU_SOURCE -D_DARWIN -I/opt/local/include -I/Users/thayer/f002s80/rst/include/base   -c fontdb.c    
fontdb.c:124:22: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
  else sprintf(fname,ptr->buf);
                     ^~~~~~~~
/usr/include/secure/_stdio.h:47:56: note: expanded from macro 'sprintf'
  __builtin___sprintf_chk (str, 0, __darwin_obsz(str), __VA_ARGS__)
                                                       ^~~~~~~~~~~
fontdb.c:124:22: note: treat the string as an argument to avoid this
  else sprintf(fname,ptr->buf);
                     ^
/Users/thayer/f002s80/rst/build/script/make.code: line 64: 33381 Segmentation fault: 11  makeall -vb ${patn} ${opt} ${src} >> ${log}.${dtval}
```

**Comment by kkotyk** [comment]
To me it just looks like thats just a compiler warning. Your real problem is that the builder actually segfaulted somehow....

**Comment by egthomas** [comment]
That's probably true.  I think I'm going to call it quits on this now.  Maybe during/after the workshop a few other people will try to compile on a Mac and we can figure it all out.

**Comment by egthomas** [comment]
Compiles on Debian, Mint, OpenSUSE, and Ubuntu virtual machines; merging.
